[package]
name = "kktix"
version = "0.1.0"
authors = ["Xavier Lau <c.estlavie@icloud.com>"]
edition = "2018"

[dependencies]
regex = "1.1.5"
reqwest = "0.9.13"
serde = "1.0.90"
serde_derive = "1.0.90"
serde_json = "1.0.39"
toml = "0.5.0"
urlparse = "0.7.3"
