[package]
name = "tumblr-exporter"
version = "0.1.0"
authors = ["Xavier Lau <c.estlavie@icloud.com>"]
edition = "2018"

[dependencies]
regex = "1.1.0"
reqwest = "0.9.9"
rumblr = "2.0.1"
serde_json = "1.0.38"